export const CHECK_OR_CREATE_CUSTOMER_REQUEST = 'CHECK_OR_CREATE_CUSTOMER_REQUEST';
export const CHECK_OR_CREATE_CUSTOMER_SUCCESS = 'CHECK_OR_CREATE_CUSTOMER_SUCCESS';
export const CHECK_OR_CREATE_CUSTOMER_FAILURE = 'CHECK_OR_CREATE_CUSTOMER_FAILURE';

